/**
 * Q-Secure | AIReportPanel.jsx
 * Phase 5 — AI narrative report display panel
 * Shows executive summary, technical analysis, key findings, immediate actions
 * Badge: "Generated by Groq LLM" or "Generated by Rule Engine"
 */

import { useState } from 'react';
import { ChevronDown, ChevronUp, Download, Cpu, BookOpen } from 'lucide-react';

function CollapsibleSection({ title, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div style={{ marginBottom: 12 }}>
      <div
        onClick={() => setOpen(o => !o)}
        style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '10px 14px',
          background: 'rgba(255,255,255,0.04)',
          borderRadius: open ? '8px 8px 0 0' : 8,
          cursor: 'pointer',
          border: '1px solid rgba(255,255,255,0.08)',
          borderBottom: open ? '1px solid rgba(255,255,255,0.04)' : undefined,
        }}
      >
        <span style={{ fontWeight: 700, fontSize: 13 }}>{title}</span>
        {open ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
      </div>
      {open && (
        <div style={{
          padding: '14px 16px',
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.08)',
          borderTop: 'none',
          borderRadius: '0 0 8px 8px',
        }}>
          {children}
        </div>
      )}
    </div>
  );
}

export default function AIReportPanel({ narrative, onDownload, loading }) {
  if (loading) {
    return (
      <div style={{
        display: 'flex', flexDirection: 'column', alignItems: 'center',
        padding: 40, gap: 16, color: 'var(--text-muted)',
      }}>
        <div style={{
          width: 40, height: 40,
          border: '3px solid rgba(255,255,255,0.1)',
          borderTop: '3px solid var(--color-primary, #c41230)',
          borderRadius: '50%',
          animation: 'spin 0.8s linear infinite',
        }} />
        <p style={{ margin: 0, fontSize: 14 }}>Analyzing cryptographic posture...</p>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  if (!narrative) {
    return (
      <div style={{ padding: 24, textAlign: 'center', color: 'var(--text-muted)', fontSize: 14 }}>
        Click "Generate Report" to produce an AI-powered analysis.
      </div>
    );
  }

  const isGroq = narrative.generated_by === 'GROQ_LLM';

  return (
    <div>
      {/* Generation badge */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16, flexWrap: 'wrap', gap: 8 }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: 8,
          padding: '6px 12px',
          background: isGroq ? 'rgba(200,146,42,0.15)' : 'rgba(96,165,250,0.1)',
          border: `1px solid ${isGroq ? 'rgba(200,146,42,0.3)' : 'rgba(96,165,250,0.2)'}`,
          borderRadius: 99,
        }}>
          {isGroq ? <Cpu size={13} color="#f5c842" /> : <BookOpen size={13} color="#60a5fa" />}
          <span style={{ fontSize: 12, fontWeight: 700, color: isGroq ? '#f5c842' : '#60a5fa' }}>
            {isGroq ? `Generated by Groq LLM (${narrative.model_used || 'llama-3.3-70b-versatile'})` : 'Generated by Rule Engine'}
          </span>
        </div>
        {onDownload && (
          <button
            onClick={onDownload}
            style={{
              display: 'flex', alignItems: 'center', gap: 6,
              padding: '6px 14px',
              background: 'rgba(200,146,42,0.15)',
              border: '1px solid rgba(200,146,42,0.3)',
              borderRadius: 8,
              color: '#f5c842',
              fontSize: 12,
              fontWeight: 700,
              cursor: 'pointer',
            }}
          >
            <Download size={13} />
            Download PDF
          </button>
        )}
      </div>

      {/* Executive Summary */}
      {narrative.executive_summary && (
        <div style={{
          background: 'rgba(196,18,48,0.06)',
          border: '1px solid rgba(196,18,48,0.2)',
          borderRadius: 10,
          padding: '16px 18px',
          marginBottom: 14,
        }}>
          <div style={{ fontSize: 11, color: '#c41230', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 8 }}>
            Executive Summary
          </div>
          <p style={{ margin: 0, fontSize: 14, lineHeight: 1.6, color: 'var(--text-primary)' }}>
            {narrative.executive_summary}
          </p>
        </div>
      )}

      {/* Key Findings */}
      {narrative.key_findings?.length > 0 && (
        <div style={{ marginBottom: 14 }}>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 8 }}>
            Key Findings
          </div>
          <ul style={{ margin: 0, paddingLeft: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 }}>
            {narrative.key_findings.map((finding, i) => (
              <li key={i} style={{
                display: 'flex', alignItems: 'flex-start', gap: 8,
                padding: '8px 12px',
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(255,255,255,0.07)',
                borderRadius: 7,
                fontSize: 13,
              }}>
                <span style={{ color: '#ff7a00', fontWeight: 800, flexShrink: 0 }}>{i + 1}.</span>
                {finding}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Immediate Actions */}
      {narrative.immediate_actions?.length > 0 && (
        <div style={{ marginBottom: 14 }}>
          <div style={{ fontSize: 11, color: '#22c55e', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 8 }}>
            Immediate Actions
          </div>
          <ol style={{ margin: 0, paddingLeft: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 }}>
            {narrative.immediate_actions.map((action, i) => (
              <li key={i} style={{
                display: 'flex', alignItems: 'flex-start', gap: 8,
                padding: '8px 12px',
                background: 'rgba(34,197,94,0.06)',
                border: '1px solid rgba(34,197,94,0.15)',
                borderRadius: 7,
                fontSize: 13,
              }}>
                <span style={{ color: '#22c55e', fontWeight: 800, flexShrink: 0 }}>→</span>
                {action}
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Technical Analysis (collapsible) */}
      {narrative.technical_analysis && (
        <CollapsibleSection title="Technical Analysis">
          <pre style={{
            margin: 0,
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 12,
            color: 'var(--text-secondary, #9aa5bf)',
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
            lineHeight: 1.6,
          }}>
            {narrative.technical_analysis}
          </pre>
        </CollapsibleSection>
      )}

      <div style={{ marginTop: 12, fontSize: 11, color: 'var(--text-muted)', textAlign: 'right' }}>
        Generated: {narrative.generated_at ? new Date(narrative.generated_at).toLocaleString() : '—'}
      </div>
    </div>
  );
}
